// arch-tag: ff400732-6e5d-4dc4-88c7-3900d40da11e
package de.yvert.cr.stdlib;

/** 
 * This class serves as a common parent classes for all
 * classes generated by JavaCodeGen due to struct declarations.
 */
public abstract class StructClass 
{
	// OK
}
